name: flutter_cek_ongkir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: 4.6.6
  flutter:
    sdk: flutter
  http: ^1.2.1
  dropdown_search: ^5.0.6
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon_ongkir.png'
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: 'assets/icon_ongkir.png'
    background_color: '#hexcode'
    theme_color: '#hexcode'
  windows:
    generate: true
    image_path: 'assets/icon_ongkir.png'
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: 'assets/icon_ongkir.png'
